# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dof < Formula
  desc "Manage your dot files as a git bare repo"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.73"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/dof/releases/download/0.73/dof_0.73_Darwin_x86_64.tar.gz"
      sha256 "a762071de9ad8128f4ea4158ce507af2f4c3b47bd6e4518b4a0cb09541c35770"

      def install
        bin.install "dof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/dof/releases/download/0.73/dof_0.73_Darwin_arm64.tar.gz"
      sha256 "cac9861c2469b3cb3d77606e9c75a912ebb7db88f31dae7b56dcdc13377b06d7"

      def install
        bin.install "dof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/dof/releases/download/0.73/dof_0.73_Linux_x86_64.tar.gz"
      sha256 "76536fd15a630bcf5dfacd6c26ece43465118959d3c915c1806650665bbaa33e"

      def install
        bin.install "dof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/dof/releases/download/0.73/dof_0.73_Linux_arm64.tar.gz"
      sha256 "9b9aec1ac3f47a4f201606133b18f20d7c2e7d2777b67eb749387b56e5db808c"

      def install
        bin.install "dof"
      end
    end
  end
end
