# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivyops < Formula
  desc "Trivyops can be used to scan GitLab for trivy results"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/trivyops/releases/download/v0.3/trivyops_0.3_Darwin_arm64.tar.gz"
      sha256 "289367e0b2d3e8cb4759119a20334b8c39551b59b6fb7d1f5850ad415bbd7a80"

      def install
        bin.install "trivyops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/trivyops/releases/download/v0.3/trivyops_0.3_Darwin_x86_64.tar.gz"
      sha256 "38635c51be7757f3b3f7734c3d60a88ed0a9a0e3e664b1ec973b82b2c8ef02ad"

      def install
        bin.install "trivyops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/trivyops/releases/download/v0.3/trivyops_0.3_Linux_arm64.tar.gz"
      sha256 "b1cca1c166fce28e22af7e1bdc9b65ae583dd598a9c69746d7df92c891e2f1bc"

      def install
        bin.install "trivyops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/trivyops/releases/download/v0.3/trivyops_0.3_Linux_x86_64.tar.gz"
      sha256 "d4a68750d1b9a0c52576537cf97a285a10fe2be4943e4e948de5dbb3405dfdd1"

      def install
        bin.install "trivyops"
      end
    end
  end
end
