# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivyops < Formula
  desc "This tool can be used to scan GitLab for trivy results"
  homepage "https://github.com/steffakasid/trivyops"
  version "0.27"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/trivyops/releases/download/v0.27/trivyops_0.27_darwin_amd64.tar.gz"
      sha256 "f27951ca73da5e13230ef952d604ca271585a72e4ec6edc110d5b72a6a4f5af0"

      def install
        bin.install "trivyops"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/trivyops/releases/download/v0.27/trivyops_0.27_darwin_arm64.tar.gz"
      sha256 "386031c1333c647db2215240fbcdf0a9f26b808d0117127cfafcb3aa503b4366"

      def install
        bin.install "trivyops"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/trivyops/releases/download/v0.27/trivyops_0.27_linux_amd64.tar.gz"
        sha256 "da5b909633783def2ff27caab5b7311f09654987ec8952b0b89b3d76fb27030a"

        def install
          bin.install "trivyops"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/trivyops/releases/download/v0.27/trivyops_0.27_linux_arm64.tar.gz"
        sha256 "76ced414072cd43a85c921b6e2c4c67b2cd28b86710d5f962a792300451a1797"

        def install
          bin.install "trivyops"
        end
      end
    end
  end
end
